
version: 2

sources:
  - name: staging
    database: football-465805
    schema: test
    tables:
      - name: appearances
      - name: club_games
      - name: clubs
      - name: competitions
      - name: game_lineups
      - name: games
      - name: player_valuations
      - name: players
      - name: transfers


models:
  - name: stg_games
    description: "The games asset contains one row per game in the dataset. All games are tied to one particular competition"
    columns:
      - name: game_id
        data_type: int64
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: competition_id
        data_type: string
        description: ""
        tests:
          - relationships:
              to: ref('stg_competitions')
              field: competition_id
              severity: warn
        

      - name: date
        data_type: date
        description: ""

      - name: season
        data_type: int64
        description: ""

      - name: round
        data_type: string
        description: ""

      - name: home_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: away_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: home_club_goals
        data_type: int64
        description: ""

      - name: away_club_goals
        data_type: int64
        description: ""

      - name: home_club_manager_name
        data_type: string
        description: ""

      - name: away_club_manager_name
        data_type: string
        description: ""

      - name: stadium
        data_type: string
        description: ""

      - name: attendance
        data_type: int64
        description: ""

      - name: referee
        data_type: string
        description: ""

      - name: competition_type
        data_type: string
        description: ""

  - name: stg_clubs
    description: "The clubs asset contains one row per club in the dataset. All clubs are tied to one particular competition."
    columns:
      - name: club_id
        data_type: int64
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: club_name
        data_type: string
        description: ""

      - name: domestic_competition_id
        data_type: string
        description: ""
        tests:
          - relationships:
              to: ref('stg_competitions')
              field: competition_id
              severity: warn
        

      - name: stadium_name
        data_type: string
        description: ""

      - name: stadium_seats
        data_type: int64
        description: ""

  - name: stg_competitions
    description: "The competitions asset contains one row per competition in the dataset, including national leagues, cups and intern"
    columns:
      - name: competition_id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: competition_name
        data_type: string
        description: ""

      - name: competition_type
        data_type: string
        description: ""

      - name: country_name
        data_type: string
        description: ""

      - name: confederation
        data_type: string
        description: ""

      - name: is_major_national_league
        data_type: boolean
        description: ""

  - name: stg_game_lineups
    description: ""
    columns:
      - name: game_lineups_id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: date
        data_type: date
        description: ""

      - name: game_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_games')
              field: game_id
              severity: warn

      - name: player_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_players')
              field: player_id
              severity: warn

      - name: club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: player_name
        data_type: string
        description: ""

      - name: type
        data_type: string
        description: ""
        tests:
          - accepted_values:
              values: ['substitutes', 'starting_lineup']
              severity: warn

      - name: position
        data_type: string
        description: ""

      - name: number
        data_type: string
        description: ""

      - name: team_captain
        data_type: int64
        description: ""

  - name: stg_appearances
    description: "The appearances asset contains one record per player appearance. That is, one record per player per game played."
    columns:
      - name: appearance_id
        data_type: string
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: game_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_games')
              field: game_id
              severity: warn

      - name: player_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_players')
              field: player_id
              severity: warn

      - name: player_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: player_current_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: date
        data_type: date
        description: ""

      - name: player_name
        data_type: string
        description: ""

      - name: competition_id
        data_type: string
        description: ""
        tests:
          - relationships:
              to: ref('stg_competitions')
              field: competition_id
              severity: warn

      - name: yellow_cards
        data_type: int64
        description: ""

      - name: red_cards
        data_type: int64
        description: ""

      - name: goals
        data_type: int64
        description: ""

      - name: assists
        data_type: int64
        description: ""

      - name: minutes_played
        data_type: int64
        description: ""

  - name: stg_players
    description: "The players asset contains one row per player in the dataset."
    columns:
      - name: player_id
        data_type: int64
        description: ""
        tests:
          - unique:
              severity: warn
          - not_null:
              severity: warn

      - name: player_name
        data_type: string
        description: ""

      - name: last_season
        data_type: int64
        description: ""

      - name: current_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: country_of_birth
        data_type: string
        description: ""

      - name: date_of_birth
        data_type: date
        description: ""

      - name: age
        data_type: int64
        description: ""

      - name: position
        data_type: string
        description: ""

      - name: foot
        data_type: string
        description: ""

      - name: height_in_cm
        data_type: int64
        description: ""

      - name: market_value_in_eur
        data_type: int64
        description: ""

      - name: highest_market_value_in_eur
        data_type: int64
        description: ""

  - name: stg_player_valuations
    description: "The player_valuations asset contains one row per player value record."
    columns:
      - name: player_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_players')
              field: player_id
              severity: warn

      - name: date
        data_type: date
        description: ""

      - name: market_value_in_eur
        data_type: int64
        description: ""

      - name: current_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

  - name: stg_club_games
    description: "The club_games asset is an alternative representation of a season games from the clubs point of view."
    columns:
      - name: game_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_games')
              field: game_id
              severity: warn

      - name: club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: own_goals
        data_type: int64
        description: ""

      - name: opponent_id
        data_type: int64
        description: ""

      - name: opponent_goals
        data_type: int64
        description: ""

      - name: hosting
        data_type: string
        description: ""

      - name: is_win
        data_type: int64
        description: ""

  - name: stg_transfers
    description: ""
    columns:
      - name: player_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_players')
              field: player_id
              severity: warn

      - name: transfer_date
        data_type: date
        description: ""

      - name: transfer_season
        data_type: string
        description: ""

      - name: from_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: to_club_id
        data_type: int64
        description: ""
        tests:
          - relationships:
              to: ref('stg_clubs')
              field: club_id
              severity: warn

      - name: transfer_fee
        data_type: float64
        description: ""

      - name: market_value_in_eur
        data_type: float64
        description: ""